sentence=input("enter the sentence:")

print("Original sentence:", sentence)
print("Total characters(with spaces):", len(sentence))
print("Total characters(without spaces):", len(sentence.replace(" ", "")))
print("Total words:",len(sentence.split()))
print("Uppercase:",sentence.upper())
print("Lowercase:",sentence.lower())
print("Title Case:",sentence.title())
print("First word:", sentence.split()[0] if sentence.split() else "No words in the sentence")
print("Last word :", sentence.split()[-1] if sentence.split() else "No words in the sentence")
print("Reversed sentence:", sentence[::-1])